###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

  mysql:
    image: mysql:5.7.30
    container_name: vinskit-mysql
    command: --default-authentication-plugin=mysql_native_password
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=vinskit_local
      - MYSQL_USER=vinskit_local
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"

  webserver:
    build: phpdocker/apache
    container_name: vinskit-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/apache/sites-avaiable/vinskit.local.conf:/usr/local/apache2/conf/vinskit.local.conf
    ports:
      - "80:80"

  php-fpm:
    build: phpdocker/php-fpm
    container_name: vinskit-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
